// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutosizeController from "./autosize_controller"
application.register("autosize", AutosizeController)

import ChoicesjsController from "./choicesjs_controller"
application.register("choicesjs", ChoicesjsController)

import ConfettiController from "./confetti_controller"
application.register("confetti", ConfettiController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotasController from "./notas_controller"
application.register("notas", NotasController)

import ParticipacaoLinkController from "./participacao_link_controller"
application.register("participacao-link", ParticipacaoLinkController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
